name: EconomyPlus
main: me.Gugino.economy.EconomyPlus
version: 0.1
description: >
             FusionScape Custom Plugin.
commands:
  ep-pay:
    description: shows a GUI with all possible warps.