name: EconomyPlus
main: me.Gugino.economy.EconomyPlus
version: 0.1
description: >
             Simple Economy Plugin.
commands:
  ep:
    description: Shows list of all possible commands.
  ep-pay:
    description: Allows players to send money to each other.